# Numpy Practice 

In [2]:
# including the numpy library

In [3]:
import numpy as np

In [157]:
np.__version__

'1.21.1'

In [4]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
b=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(b)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [6]:
b.ndim

2

In [7]:
b.shape  # get the shape

(2, 5)

In [8]:
# get type
b.dtype

dtype('int32')

In [9]:
# get size of element
a.itemsize

4

In [10]:
# get total size
a.size *a.itemsize

16

In [11]:
# get total size
a.nbytes

16

In [12]:
 a.size

4

# Accessing / changing specific elements,rows,column, etc

In [13]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# get the Specfic values
c[1,5]

13

In [15]:
c[0,3]

4

In [16]:
c[1,2:4]

array([10, 11])

In [17]:
c[0:,4:]

array([[ 5,  6,  7],
       [12, 13, 14]])

In [18]:
c[:,2]

array([ 3, 10])

In [19]:
c[0,1:6:2]

array([2, 4, 6])

In [20]:
c[1,4]=22

In [21]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 22, 13, 14]])

In [22]:
c[:,2]=55

In [23]:
c

array([[ 1,  2, 55,  4,  5,  6,  7],
       [ 8,  9, 55, 11, 22, 13, 14]])

In [24]:
c[:,1]=[44,66]
c

array([[ 1, 44, 55,  4,  5,  6,  7],
       [ 8, 66, 55, 11, 22, 13, 14]])

In [25]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
d[0,1,1]

4

In [27]:
d[:,:,0]   # accessing all the list element

array([[1, 3],
       [5, 7]])

In [28]:
d[:,:2,1]

array([[2, 4],
       [6, 8]])

# replace 

In [29]:
d[:,1,:]=[[11,22],[55,66]]

In [30]:
d

array([[[ 1,  2],
        [11, 22]],

       [[ 5,  6],
        [55, 66]]])

# intialize differefnt types of array

In [31]:
# all zeros matrix
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
#full fuction
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [36]:
c.shape  # taken from top of the code

(2, 7)

In [37]:
np.full(c.shape,22)

array([[22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22]])

In [38]:
# same of above code in different way

In [39]:
np.full_like(c,22)

array([[22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22]])

In [40]:
# random Decimal numbers
np.random.rand(4,2)*100

array([[24.57879413,  1.60061023],
       [63.35428287, 50.74117428],
       [52.29362526,  4.15029191],
       [24.98842145, 91.31927253]])

In [41]:
#existed shape random value
np.random.random_sample(c.shape)

array([[0.81383761, 0.75172378, 0.37399405, 0.01193833, 0.68365868,
        0.36955359, 0.17013927],
       [0.85866099, 0.8293754 , 0.76540539, 0.67357992, 0.43677673,
        0.89843131, 0.55620589]])

In [42]:
# Random integer values
np.random.randint(3,size=(4,4))

array([[0, 2, 0, 0],
       [0, 0, 2, 2],
       [2, 0, 2, 1],
       [2, 0, 2, 0]])

In [43]:
# identity Matrix
np.identity(4) # matric 4*4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:

arr=np.array([[1,2,3]])
r=np.repeat(arr,3, axis=1)
r

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [45]:
# pattern making

output=np.ones((5,5))
print(output)
print()
print("==========================================")

z=np.zeros((3,3))
z[1,1]=9
print(z)
print()
print("==========================================")

output[1:-1,1:-1]=z
print()
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
####Be careful when coping arrrays
a=np.array([1,2,3])  // it will change the orginal value also be careful
b=a
print(a)
b[1]=22
print(a)

SyntaxError: invalid syntax (Temp/ipykernel_6288/2872077582.py, line 2)

In [47]:
a=np.array([1,2,3])
b=a.copy()
b

array([1, 2, 3])

# Calculations

In [48]:
e=np.array([1,2,3,4])
e

array([1, 2, 3, 4])

In [49]:
e+2

array([3, 4, 5, 6])

In [50]:
e-2

array([-1,  0,  1,  2])

In [51]:
e*2

array([2, 4, 6, 8])

In [52]:
e**2

array([ 1,  4,  9, 16], dtype=int32)

In [53]:
f=np.array([1,0,1,0])
e+f

array([2, 2, 4, 4])

In [54]:
np.sin(e)  # same as cos also will be calclated  

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# ##Liner Algebra

In [55]:
a=np.ones((2,3))
print(a)
h=np.full((3,2),2)
print(h)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [56]:
np.matmul(a,h)

array([[6., 6.],
       [6., 6.]])

In [57]:
# find the determinant

c=np.identity(3)
print(c)
print("--------------------------")
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------


1.0

# statistics

In [58]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.min(arr,axis=0)  # vary the axis

array([1, 2, 3])

In [60]:
arr.min()

1

In [61]:
arr.max()

6

In [62]:
np.max(arr,axis=0) # vary the axis

array([4, 5, 6])

In [63]:
np.sum(arr)

21

In [64]:
np.sum(arr,axis=0) # vary the axis and remove the axis

array([5, 7, 9])

# ReOrganize Array

In [65]:
arr1=np.array([[1,5,8,9],[4,8,4,5]])
arr1

array([[1, 5, 8, 9],
       [4, 8, 4, 5]])

In [66]:
arr2=arr1.reshape((8,1))
print(arr2)
print()
print("-------------------------------")
print()
arr3=arr1.reshape((2,2,2))
print(arr3)

[[1]
 [5]
 [8]
 [9]
 [4]
 [8]
 [4]
 [5]]

-------------------------------

[[[1 5]
  [8 9]]

 [[4 8]
  [4 5]]]


# accessing the txt file by using the  np.genfromtxt()

In [67]:
 data=np.genfromtxt('C:\\Users\\Ramireddy Chandu\\Downloads\\NumPy-master\\data.txt',delimiter=",")

In [68]:
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [69]:
data.astype('int16')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int16)

### advanced Index

In [70]:
data>0 


array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True]])

In [71]:
data[data>50]=-1

In [72]:
data.astype('int32')

array([[ 1, 13, 21, 11, -1, -1,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,
         4,  5],
       [ 3, 42, 12, 33, -1, -1,  4, -1,  6,  4,  3,  4,  5,  6,  7,  0,
        11, 12],
       [ 1, 22, 33, 11, -1, 11,  2,  1, -1,  0,  1,  2,  9,  8,  7,  1,
        -1, -1]])

In [73]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,3,8]])

[2 4 9]


In [74]:
np.any(data>50, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [75]:
np.all(data>50, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [76]:
print(((data>40) & (data<90)))

[[False False False False False False False False False False False False
  False False False False False False]
 [False  True False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False]]


In [77]:
print((~(data>60) & (data<90)))

[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True]]


In [78]:
karr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
karr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [79]:
print(karr[[0,1,2,3],[1,2,3,4]])  #d diagonal type

[ 2  8 14 20]


In [80]:
karr[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [81]:
import random


In [82]:
rng = np.random.default_rng(12345)
rng

Generator(PCG64) at 0x199A63C9580

# Iterating  Arrays

In [83]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [84]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
         for z in y:
        
              print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [85]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [86]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [87]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [88]:
#Concatenate of numpy array with existing array
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])

array=np.concatenate((array1,array2))
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [89]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print()
print("============================")
print(arr2)
print("============================")
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions

In [90]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])


arrs=np.stack((arr1,arr2),axis=1)
print(arrs)


print("===========================")
arr=np.stack((arr1,arr2))
print(arr)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [91]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arra = np.hstack((arr1, arr2))
array = np.vstack((arr1, arr2))
arr = np.dstack((arr1, arr2))
print(arra)
print()
print("=========================")
print(array)
print("==========================")
print(arr)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [92]:
# splitting of an array

arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [93]:
newarr[0]

array([1, 2])

# NumPy Searching Arrays

In [95]:
arr=np.array([4,2,3,4,5,6,7,4])

x=np.where(arr==4)
print(x)

(array([0, 3, 7], dtype=int64),)


In [96]:
y=np.where(arr%2==0)
y

(array([0, 1, 3, 5, 7], dtype=int64),)

In [97]:
arr1=np.array([5,6,8,4,1,2,9,7,5])
arr1

array([5, 6, 8, 4, 1, 2, 9, 7, 5])

In [102]:
nwarray=np.searchsorted(arr,7)
newarray=np.searchsorted(arr,7,side="right")
print(newarray)
nwarray

8


6

In [103]:
arr1

array([5, 6, 8, 4, 1, 2, 9, 7, 5])

In [104]:
np.sort(arr1)

array([1, 2, 4, 5, 5, 6, 7, 8, 9])

In [106]:

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


# NumPy Filter Array

In [107]:

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]




# Creating the Filter Array

In [113]:

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
   if element > 42:
    filter_arr.append(True)
   else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


# Random Numbers in NumPy

In [123]:
from numpy import random
x = random.randint(100)
print(x)

77


In [133]:
a=np.random.randint(12)
print(a)
print("++++++++++++++++++++++++++++++++")
np.random.randint(12, size=(4,4))

3
++++++++++++++++++++++++++++++++


array([[9, 2, 4, 5],
       [3, 6, 7, 0],
       [0, 0, 3, 2],
       [8, 9, 1, 3]])

In [136]:
np.random.rand()

0.614448030655664

In [139]:
random.rand(4,3)

array([[0.89443153, 0.68581645, 0.77040019],
       [0.46331396, 0.64641031, 0.29162807],
       [0.31334409, 0.48183105, 0.10468427],
       [0.6551654 , 0.15437109, 0.56127976]])

In [147]:
x=np.array([5,4,8,6,1])
k=np.random.choice(x)
k

4

In [148]:

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 7 7 5 7]
 [7 9 9 7 5]
 [5 3 3 3 5]]


In [149]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 2 3 4 1]


In [150]:

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))


[1 3 5 4 2]


In [151]:
np.around([0.37,1.64])

array([0., 2.])

In [154]:
a=np.array([1,2,533.55,655.357,7,11,65.55])
res=np.around(arr,decimals=-2)

In [155]:
res

array([0, 0, 0, 0, 0])